pipeline {
    agent any

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/tirucloud/springboot-gitops-cicd-pipeline-main.git'
            }
        }

        stage('Build') {
            steps {
                dir('Springboot-app') {
                    sh 'mvn clean package'
                }
            }
        }

stage('SonarQube Analysis') {
    steps {
        dir('Springboot-app') {
            withSonarQubeEnv('sonar-server') {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    sh '''
                        mvn clean verify \
                        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                        -Dsonar.projectName=demo \
                        -Dsonar.projectKey=demo \
                        -Dsonar.token=$SONAR_TOKEN
                    '''
                }
            }
        }
    }
}

stage('Quality Gate') {
    steps {
        timeout(time: 10, unit: 'MINUTES') {
            script {
                echo 'Waiting for SonarQube Quality Gate...'

                def qg = waitForQualityGate()

                echo "SonarQube Quality Gate Status: ${qg.status}"

                if (qg.status != 'OK') {
                    error "Pipeline failed - SonarQube Quality Gate status: ${qg.status}"
                }

                echo 'SonarQube Quality Gate PASSED'
            }
        }
    }
}



        stage('Docker Build') {
            steps {
                dir('Springboot-app') {
                    sh 'docker build -t tirucloud/springboot-gitops:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-token',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push tirucloud/springboot-gitops:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
